replicaCount: 1

image:
  repository: ghcr.io/iazhan/metapi-plus
  tag: latest
  digest: ""
  pullPolicy: Always

service:
  type: NodePort
  port: 4000
  nodePort: 30400

persistence:
  hostPath: /opt/1panel/docker/compose/metapihub/data

env:
  authToken: ""
  proxyToken: ""
  dbType: postgres
  dbUrl: ""
  dbSsl: "false"
  dataDir: /app/data
  port: "4000"
  tz: Asia/Shanghai
  checkinCron: "0 8 * * *"
  checkinEnabled: "true"
  balanceRefreshCron: "0 * * * *"
  balanceRefreshEnabled: "true"
  accountGroupRateRefreshEnabled: "true"
  accountGroupRateRefreshIntervalMinutes: "30"
  deployHelperToken: ""
